apiVersion: apps/v1
kind: Deployment

metadata:
  name: rabbitmq-consumer-deployment
  labels:
    run: rabbitmq-consumer
    app: techtalks
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rabbitmq-consumer

  template:
    metadata:
      labels:
        run: rabbitmq-consumer
        app: rabbitmq-consumer
    spec:
      containers:
        - name: rabbitmq-consumer
          image: genocs/rabbitconsumer:1.3
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: RABBITMQ_HOST_NAME
              value: "rabbitmq-headless"
            - name: RABBITMQ_USER_NAME
              value: "user"
            - name: RABBITMQ_PASSWORD
              value: "PASSWORD"
            - name: RABBITMQ_BATCH_SIZE
              value: "50"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "20m" #2% of a core
              memory: "20Mi"
            limits:
              cpu: "20m" #2% of a core
              memory: "20Mi"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
