apiVersion: v1
kind: Pod

metadata:
  name: rabbitmq-consumer-pod
  labels:
    run: rabbitmq-consumer

spec:
  containers:
    - name: rabbitmq-consumer
      image: genocs/rabbitconsumer:1.4
      env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: RABBITMQ_HOST_NAME
          valueFrom:
            secretKeyRef:
              name: secret-file
              key: RABBITMQ_HOST_NAME
        - name: RABBITMQ_USER_NAME
          valueFrom:
            secretKeyRef:
              name: secret-file
              key: RABBITMQ_USER_NAME
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-file
              key: RABBITMQ_PASSWORD
        - name: RABBITMQ_BATCH_SIZE
          value: "50"
      resources:
        requests:
          cpu: "200m" #20% of a core
          memory: "20Mi"
        limits:
          cpu: "500m" #50% of a core
          memory: "50Mi"
  restartPolicy: Always
