apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo-external-producer  
  labels:
    run: demo-external-producer

spec:
  replicas: 1
  selector:
    matchLabels:
      run: demo-external-producer

  template:
    metadata:
      labels:
        run: demo-external-producer
    spec:
      containers:
        - name: rabbitmqproducer
          image: genocs/rabbitmqproducer:1.0
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: RABBITMQ_HOST_NAME
              value: "{{ .Values.rabbitmq.hostname}}"
            - name: RABBITMQ_VIRTUAL_HOST
              value: "{{ .Values.rabbitmq.virtualhost}}"
            - name: RABBITMQ_USER_NAME
              value: "{{ .Values.rabbitmq.username}}"
            - name: RABBITMQ_PASSWORD
              value: "{{ .Values.rabbitmq.password}}"
            - name: ApiClients__InternalApi
              value: "http://demo-internal-producer-service"              
          ports:
            - containerPort: {{ .Values.rabbitmqproducer.containerPort }}
              protocol: TCP
          resources:
            requests:
              cpu: "10m" #1% of a core
              memory: "200Mi"
            limits:
              cpu: "50m" #5% of a core
              memory: "500Mi"
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
