apiVersion: apps/v1
kind: Deployment

metadata:
  name: rabbitmq-producer-deployment
  # namespace: default
  labels:
    run: rabbitmq-producer
    app: apprabbitproducer

spec:
  replicas: 1
  selector:
    matchLabels:
      run: rabbitmq-producer

  template:
    metadata:
      labels:
        run: rabbitmq-producer
        app: apprabbitproducer
    spec:
      containers:
        - name: rabbitproducer
          image: genocs/rabbitproducer:1.3
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: RABBITMQ_HOST_NAME
              value: "rabbitmq"
            - name: RABBITMQ_USER_NAME
              value: "user"
            - name: RABBITMQ_PASSWORD
              value: "PASSWORD"
            - name: ApiClients__InternalApi
              value: "http://rabbitmq-producer-int-service"
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: "10m" #1% of a core
              memory: "200Mi"
            limits:
              cpu: "50m" #5% of a core
              memory: "500Mi"
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
