global:
  scrape_interval:     5s
  evaluation_interval: 30s
scrape_configs:
- job_name: application-producer-scraper
  honor_labels: true
  static_configs:
  - targets: ['rabbitmq-producer-service:6001']