apiVersion: v1
kind: Secret
metadata:
  name: secret-file
type: Opaque
data:
  APPLICATIONINSIGHT_CONNECTIONSTRING: SW5zdHJ1bWVudGF0aW9uS2V5PWYyOGI4YThjLWJmNjUtNDRhNi05OTc2LWU1NjYxM2ZlZjQ2NjtJbmdlc3Rpb25FbmRwb2ludD1odHRwczovL3dlc3RldXJvcGUtNS5pbi5hcHBsaWNhdGlvbmluc2lnaHRzLmF6dXJlLmNvbS87TGl2ZUVuZHBvaW50PWh0dHBzOi8vd2VzdGV1cm9wZS5saXZlZGlhZ25vc3RpY3MubW9uaXRvci5henVyZS5jb20v
  RABBITMQ_HOST_NAME: cmFiYml0bXEtaGVhZGxlc3M=
  RABBITMQ_USER_NAME: dXNlcg==
  RABBITMQ_PASSWORD: UEFTU1dPUkQ=
