version: '3.9'

services:
  rabbitproducer:
    image: genocs/rabbitproducer:1.3
    hostname: rabbitproducer
    container_name: rabbitproducer
    ports:
      - 6001:80
    networks:
      - genocs
    environment:
      - RABBITMQ_HOST_NAME=rabbitmq
      - RABBITMQ_USER_NAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_BATCH_SIZE=50

  rabbitconsumer:
    image: genocs/rabbitconsumer:1.3
    hostname: rabbitconsumer
    container_name: rabbitconsumer
    ports:
      - 6002:80
    networks:
      - genocs
    environment:
      - RABBITMQ_HOST_NAME=rabbitmq
      - RABBITMQ_USER_NAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_BATCH_SIZE=50      

  testmetrics:
    image: genocs/testmetrics
    hostname: testmetrics
    container_name: testmetrics
    ports:
      - 6003:80
    networks:
      - genocs

networks:
  genocs:
    name: genocs-network
    external: true
