version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit_node_1
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692      
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - genocs
    # network_mode: host

  mongo:
    image: mongo
    hostname: mongodb_node_1
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - genocs
    # network_mode: host
    volumes:
      - mongo:/var/lib/data/db

  redis:
    image: redis
    hostname: redis_node_1        
    container_name: redis_cache
    ports:
      - 6379:6379
    networks:
      - genocs
    # network_mode: host
    volumes:
      - redis:/data

networks:
  genocs:
    name: genocs-network

volumes:
  mongo:
    driver: local
  rabbitmq:
    driver: local
  redis:
    driver: local
