version: "3.8"

services:
  consul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500
    networks:
      - genocs
    # network_mode: host
    volumes:
      - consul:/consul/data

  fabio:
    image: fabiolb/fabio
    container_name: fabio
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    networks:
      - genocs
    # network_mode: host
    ports:
      - 9998:9998
      - 9999:9999

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - genocs
    # network_mode: host
    volumes:
      - grafana:/var/lib/grafana

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - genocs
    # network_mode: host
    volumes:
      - influxdb:/var/lib/influxdb

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
    networks:
      - genocs
    # network_mode: host

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - genocs
    # network_mode: host
    volumes:
      - prometheus:/var/lib/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  seq:
    image: datalust/seq
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    networks:
      - genocs
    # network_mode: host
    volumes:
      - seq:/data

  vault:
    image: vault
    container_name: vault
    ports:
      - 8200:8200
    networks:
      - genocs
    # network_mode: host
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK

networks:
  genocs:
    name: genocs-network
    external: true

volumes:
  consul:
    driver: local
  esdata:
    driver: local
  grafana:
    driver: local
  influxdb:
    driver: local
  prometheus:
    driver: local
  seq:
    driver: local
