version: "3.9"

services:
  neo4j:
    image: neo4j:community ## The community edition
    hostname: nhp_neo4j ## The name of the image
    container_name: neo4j_db
    ports: ## publish ports to have Web UI
      - 17474:7474
      - 7687:7687
      - 7474:7474
    volumes: ## adds folder with login/password
      - neo4j_data:/data ## local data ./neo4j/data:/data
      - neo4j_logs:/logs ## local logs ./neo4j/logs:/logs
#      - ./neo4j/data:/data    ## host data ./neo4j/data:/data
#      - ./neo4j/logs:/logs    ## host logs ./neo4j/logs:/logs

networks:
  genocs:
    name: genocs-network
    external: true

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
