global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  #  - job_name: 'docker'
  #    static_configs:
  #      - targets: ['host.docker.internal:9393'] # Former docker.for.win.localhost. Check: https://github.com/dotnet-architecture/eShopOnContainers/issues/1397
  - job_name: "rabbitmq-server"
    static_configs:
      - targets: ["rabbitmq:15692"]
#  - job_name: 'rabbitproducer'
#    static_configs:
#      - targets: ['rabbitproducer:80']
#  - job_name: 'rabbitconsumer'
#    static_configs:
#      - targets: ['rabbitconsumer:80']
#  - job_name: 'testmetrics'
#    static_configs:
#      - targets: ['testmetrics:80']
