version: "3.9"

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sql_server
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Sup3rSecretp22w!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssqlsystem:/var/opt/mssql
      - mssqluser:/var/opt/sqlserver
    networks:
      - genocs

networks:
  genocs:
    name: genocs-network
    external: true

volumes:
  mssqlsystem:
    driver: local
  mssqluser:
    driver: local
