apiVersion: v1
kind: Secret
metadata:
  name: demo-app-secret
  namespace: genocs-demo

type: Opaque
data:
  APPLICATIONINSIGHT_CONNECTION_STRING: SW5zdHJ1bWVudGF0aW9uS2V5PWZkZmU0ZmNiLWI3ZDItNDk3ZC04OGVhLTViOTZhMTg1NWYwNTtJbmdlc3Rpb25FbmRwb2ludD1odHRwczovL3dlc3RldXJvcGUtNS5pbi5hcHBsaWNhdGlvbmluc2lnaHRzLmF6dXJlLmNvbS87TGl2ZUVuZHBvaW50PWh0dHBzOi8vd2VzdGV1cm9wZS5saXZlZGlhZ25vc3RpY3MubW9uaXRvci5henVyZS5jb20v
  APPLICATIONINSIGHT_INSTRUMENTATION_KEY: ZDdlYzhlYmMtYmEyYS00ZjdmLTkwYmItYTZhYzA1ZTFmZTg4
  MONGODB_CONNECTION_STRING: bW9uZ29kYjovL2dpb3Zhbm5pX25vY2NvOlNvbG9tb24yNDEwQGNsdXN0ZXIwLXNoYXJkLTAwLTAwLWYwa3ZoLmdjcC5tb25nb2RiLm5ldDoyNzAxNyxjbHVzdGVyMC1zaGFyZC0wMC0wMS1mMGt2aC5nY3AubW9uZ29kYi5uZXQ6MjcwMTcsY2x1c3RlcjAtc2hhcmQtMDAtMDItZjBrdmguZ2NwLm1vbmdvZGIubmV0OjI3MDE3L3Rlc3Q/c3NsPXRydWUmcmVwbGljYVNldD1DbHVzdGVyMC1zaGFyZC0wJmF1dGhTb3VyY2U9YWRtaW4mcmV0cnlXcml0ZXM9dHJ1ZQ==
  RABBITMQ_CONNECTION_STRING: YW1xcHM6Ly96Y29xbWJ0ZToyaExUd0VHSEVQeTlpWGJXejlOV1NpNURaY2g4ZXExYUBmbGFtaW5nby5ybXEuY2xvdWRhbXFwLmNvbS96Y29xbWJ0ZQ==
  RABBITMQ_HOST_NAME: ZmxhbWluZ28ucm1xLmNsb3VkYW1xcC5jb20=
  RABBITMQ_VIRTUAL_HOST: emNvcW1idGU=
  RABBITMQ_USER_NAME: emNvcW1idGU=
  RABBITMQ_PASSWORD: MmhMVHdFR0hFUHk5aVhiV3o5TldTaTVEWmNoOGVxMWE=
