apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo-external-producer
  namespace: genocs-demo
  labels:
    app: demo-external-producer
    run: demo-external-producer


spec:
  replicas: 1
  selector:
    matchLabels:
      run: demo-external-producer

  template:
    metadata:
      labels:
        app: demo-external-producer
        run: demo-external-producer
    spec:
      containers:
        - name: demo-external-producer
          image: genocs/demo-producer:1.0.0
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: RABBITMQ_HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: demo-app-secret
                  key: RABBITMQ_HOST_NAME
            - name: RABBITMQ_VIRTUAL_HOST
              valueFrom:
                secretKeyRef:
                  name: demo-app-secret
                  key: RABBITMQ_VIRTUAL_HOST
            - name: RABBITMQ_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: demo-app-secret
                  key: RABBITMQ_USER_NAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-app-secret
                  key: RABBITMQ_PASSWORD
            - name: ApiClients__InternalApi
              value: "http://demo-internal-producer-service"
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: "10m" #1% of a core
              memory: "200Mi"
            limits:
              cpu: "50m" #5% of a core
              memory: "500Mi"
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst

---
apiVersion: v1
kind: Service

metadata:
  name: demo-external-producer-service
  namespace: genocs-demo
  labels:
    run: demo-external-producer
spec:
  type: LoadBalancer
  #type: ClusterIP
  ports:
    - protocol: TCP
      name: http-port
      port: 80
      targetPort: 80

  selector:
    run: demo-external-producer
