apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo-internal-producer
  namespace: genocs-demo
  labels:
    app: demo-internal-producer
    run: demo-internal-producer

spec:
  replicas: 1
  selector:
    matchLabels:
      run: demo-internal-producer

  template:
    metadata:
      labels:
        run: demo-internal-producer
    spec:
      containers:
        - name: demo-internal-producer
          image: genocs/demo-internal-producer:1.0.0
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: RABBITMQ_HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: demo-app-secret
                  key: RABBITMQ_HOST_NAME
            - name: RABBITMQ_VIRTUAL_HOST
              valueFrom:
                secretKeyRef:
                  name: demo-app-secret
                  key: RABBITMQ_VIRTUAL_HOST
            - name: RABBITMQ_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: demo-app-secret
                  key: RABBITMQ_USER_NAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-app-secret
                  key: RABBITMQ_PASSWORD
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: "10m" #1% of a core
              memory: "200Mi"
            limits:
              cpu: "50m" #5% of a core
              memory: "500Mi"
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst

---
apiVersion: v1
kind: Service

metadata:
  name: demo-internal-producer-service
  namespace: genocs-demo
spec:
  # type: LoadBalancer
  type: ClusterIP
  ports:
    - port: 80
  selector:
    run: demo-internal-producer
