apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: producer-ingress
  annotations:
    kubernetes.io/ingress.class: "azure/application-gateway"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq-producer-service
                port:
                  number: 80
