apiVersion: apps/v1
kind: Deployment

metadata:
  name: rabbitmq-producer-deployment
  labels:
    run: rabbitmq-producer

spec:
  replicas: 2
  selector:
    matchLabels:
      run: rabbitmq-producer

  template:
    metadata:
      labels:
        run: rabbitmq-producer
    spec:
      containers:
        - name: rabbitmqproducer
          image: genocs/rabbitmqproducer:1.0
          env:
            # - name: ASPNETCORE_URLS
            #   value: http://0.0.0.0:8080
            - name: RABBITMQ_HOST_NAME
              value: "{{ .Values.rabbitmq.hostname}}"
            - name: RABBITMQ_USER_NAME
              value: "{{ .Values.rabbitmq.username}}"
            - name: RABBITMQ_PASSWORD
              value: "{{ .Values.rabbitmq.password}}"
          ports:
            # - containerPort: 8080
            - containerPort: {{ .Values.rabbitmqproducer.containerPort }}
              protocol: TCP
          resources:
            requests:
              cpu: "10m" #1% of a core
              memory: "200Mi"
            limits:
              cpu: "50m" #5% of a core
              memory: "500Mi"
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
