version: '3.9'

services:
  genocs.producer:
    image: genocs/rabbitproducer:1.4
    build:
      context: src
      dockerfile: Genocs.KubernetesCourse.WebApi.dockerfile

  genocs.producer.internal:
    image: genocs/rabbitproducerint:1.4
    build:
      context: src
      dockerfile: Genocs.KubernetesCourse.Internal.WebApi.dockerfile

  genocs.consumer:
    image: genocs/rabbitconsumer:1.4
    build:
      context: src
      dockerfile: Genocs.KubernetesCourse.Worker.dockerfile
