apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  secretObjects: # [OPTIONAL] SecretObject defines the desired state of synced k8s secret objects
    - data:
        - key: RABBITMQ_HOST_NAME
          objectName: RABBITMQ_HOST_NAME # name of the mounted content to sync. This could be the object name or object alias
        - key: RABBITMQ_USER_NAME
          objectName: RABBITMQ_USER_NAME
        - key: RABBITMQ_PASSWORD
          objectName: RABBITMQ_PASSWORD
        - key: RABBITMQ_BATCH_SIZE
          objectName: RABBITMQ_BATCH_SIZE
      secretName: akvsecrets
      type: Opaque

  parameters:
    usePodIdentity: "false" # [OPTIONAL] if not provided, will default to "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "2d881d78-2c55-4b5e-ac15-b994b422734e" # [CHANGE] The Managed Identity ClientId
    keyvaultName: "kv-genocsakst" # [CHANGE] The name of the KeyVault
    # cloudName: "AzurePublicCloud" # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects: |
      array:
        - |
          objectName: RABBITMQ-HOST-NAME
          objectType: secret        # object types: secret, key or cert
          objectAlias: RABBITMQ_HOST_NAME
          #objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: RABBITMQ-USER-NAME
          objectType: secret
          objectAlias: RABBITMQ_USER_NAME
        - |
          objectName: RABBITMQ-PASSWORD
          objectType: secret
          objectAlias: RABBITMQ_PASSWORD
        - |
          objectName: RABBITMQ-BATCH-SIZE
          objectType: secret
          objectAlias: RABBITMQ_BATCH_SIZE
    # resourceGroup: "akvResourceGroup" # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    # subscriptionId: "065cf559-687c-4233-a331-564f10c8b9ed" # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: "2448c491-9325-42f1-8b00-7b041b2361ce" # [CHANGE] The tenant ID of the KeyVault
